# Pipeline Configuration

# Path to the folder containing the allele variants
VARIANT_DATA_PATH: /path/to/folder

# path to the gene definition file
GENE: /path/to/gene.yaml

# Path to barcode fasta file used for demultiplexing
BARCODES: /path/to/barcodes.fasta

# pipeline options
STAGE_PARAMS:
  HAPLOTYPER:
    ignoreBoundary: True  # insertions at start and end of sequence should be ignored
